name: pug_flutter_fcm
description: "FCM Push Provider for Pug Flutter SDK."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  firebase_messaging: ">=15.0.0 <17.0.0"
  flutter:
    sdk: flutter
  pug_flutter_sdk:
    path: ../

dev_dependencies:
  flutter_lints: ">=4.0.0 <7.0.0"
  flutter_test:
    sdk: flutter

flutter:
