// AUTOGENERATED — DO NOT EDIT.
//
// This file will be regenerated by `make typed-track` (see Task 7+).
// During Task 4 it is hand-written as a scaffold containing only `call`.

import 'configuration.dart';
import 'pug.dart';

class TrackNamespace {
  const TrackNamespace(this._pug);
  final Pug _pug;

  /// Tracks a custom event by string kind. Matches the legacy `Pug.track`
  /// signature so that `Pug.track('kind', props: ...)` continues to work.
  void call(
    String kind, {
    Map<String, Object?> props = const {},
    TrackOptions options = const TrackOptions(),
  }) {
    _pug.capture(kind, props: props, options: options);
  }
}
