// AUTOGENERATED — DO NOT EDIT.
//
// This file will be regenerated by `make typed-track` (see Task 7+).
// During Task 4 it is hand-written as a scaffold containing only `call`.

import 'package:meta/meta.dart';

import 'configuration.dart';
import 'contracts.dart';
import 'events.dart';

/// The subset of `Pug` that `TrackNamespace` depends on. `Pug` implements
/// this. Defining it here (rather than importing `Pug`) breaks the circular
/// import between `pug.dart` and the codegen-target `track_namespace.dart`.
abstract interface class TrackContext {
  void capture(
    String kind, {
    Map<String, Object?> props,
    TrackOptions options,
  });

  PugLogger get logger;
}

class TrackNamespace {
  const TrackNamespace(this._ctx);
  final TrackContext _ctx;

  /// Tracks a custom event by string kind. Matches the legacy `Pug.track`
  /// signature so that `Pug.track('kind', props: ...)` continues to work.
  void call(
    String kind, {
    Map<String, Object?> props = const {},
    TrackOptions options = const TrackOptions(),
  }) {
    _warnDiscouragedPathOnce(kind);
    _ctx.capture(kind, props: props, options: options);
  }

  static final Set<String> _hintedKinds = <String>{};

  @visibleForTesting
  static void resetHintedKindsForTest() => _hintedKinds.clear();

  void _warnDiscouragedPathOnce(String kind) {
    if (!wellKnownEventSchemas.containsKey(kind)) return;
    if (!_hintedKinds.add(kind)) return;
    final dartName = _kindToDartMethodName(kind);
    _ctx.logger.debug(
      "Pug.track('$kind', ...) — consider Pug.track.$dartName(...) for "
      'compile-time typed properties.',
    );
  }

  static String _kindToDartMethodName(String snake) {
    final parts = snake.split('_').where((p) => p.isNotEmpty).toList();
    if (parts.isEmpty) return snake; // degenerate; pass through unchanged
    if (parts.length == 1) return parts.first;
    return parts.first +
        parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
  }

  /// Tracks a `purchase` event.
  ///
  /// Named args define the required schema fields and always win over [extras].
  /// Any [extras] key that collides with a named arg is silently dropped and
  /// logged at DEBUG level.
  void purchase({
    required String productId,
    required double amount,
    required String currency,
    Map<String, Object?> extras = const {},
    TrackOptions options = const TrackOptions(),
  }) {
    _ctx.capture(
      'purchase',
      props: _merge(
        eventName: 'purchase',
        explicit: <String, Object?>{
          'productId': productId,
          'amount': amount,
          'currency': currency,
        },
        extras: extras,
      ),
      options: options,
    );
  }

  /// Merges [extras] behind [explicit], dropping any extras key that collides
  /// with an explicit named arg and logging a DEBUG message for each dropped key.
  Map<String, Object?> _merge({
    required String eventName,
    required Map<String, Object?> explicit,
    required Map<String, Object?> extras,
  }) {
    if (extras.isEmpty) return explicit;
    final result = <String, Object?>{};
    for (final entry in extras.entries) {
      if (explicit.containsKey(entry.key)) {
        _ctx.logger.debug(
          'Pug.track.$eventName: extras key "${entry.key}" overridden by explicit named arg.',
        );
        continue;
      }
      result[entry.key] = entry.value;
    }
    result.addAll(explicit);
    return result;
  }
}
