// AUTOGENERATED — DO NOT EDIT.
//
// Regenerated by `make typed-track` (see tool/generate_track_namespace.dart).

import 'well_known_event_schemas.dart';

/// String constants for every well-known mobile-applicable
/// event kind. Prefer these constants over raw kind strings — the
/// typed `Pug.track.<event>(...)` methods use them too.
class PugEventNames {
  const PugEventNames._();

  static const addToCart = 'add_to_cart';
  static const apiKeyCreated = 'api_key_created';
  static const apiKeyRevoked = 'api_key_revoked';
  static const appBackgrounded = 'app_backgrounded';
  static const appClose = 'app_close';
  static const appCrashed = 'app_crashed';
  static const appForegrounded = 'app_foregrounded';
  static const appInstall = 'app_install';
  static const appOpen = 'app_open';
  static const appUpdate = 'app_update';
  static const audioCompleted = 'audio_completed';
  static const audioPause = 'audio_pause';
  static const audioPlay = 'audio_play';
  static const audioSeeked = 'audio_seeked';
  static const audioStarted = 'audio_started';
  static const cartViewed = 'cart_viewed';
  static const chatArchived = 'chat_archived';
  static const chatAttachmentDownloaded = 'chat_attachment_downloaded';
  static const chatAttachmentUploaded = 'chat_attachment_uploaded';
  static const chatCallJoined = 'chat_call_joined';
  static const chatCallLeft = 'chat_call_left';
  static const chatCallRecordingStarted = 'chat_call_recording_started';
  static const chatCallScreenShared = 'chat_call_screen_shared';
  static const chatCallStarted = 'chat_call_started';
  static const chatCreated = 'chat_created';
  static const chatDeleted = 'chat_deleted';
  static const chatJoined = 'chat_joined';
  static const chatLeft = 'chat_left';
  static const chatMemberAdded = 'chat_member_added';
  static const chatMemberMuted = 'chat_member_muted';
  static const chatMemberRemoved = 'chat_member_removed';
  static const chatMemberRoleChanged = 'chat_member_role_changed';
  static const chatMessageDeleted = 'chat_message_deleted';
  static const chatMessageEdited = 'chat_message_edited';
  static const chatMessageFailed = 'chat_message_failed';
  static const chatMessagePinned = 'chat_message_pinned';
  static const chatMessageRead = 'chat_message_read';
  static const chatMessageReceived = 'chat_message_received';
  static const chatMessageSent = 'chat_message_sent';
  static const chatMessageUnpinned = 'chat_message_unpinned';
  static const chatReactionAdded = 'chat_reaction_added';
  static const chatReactionRemoved = 'chat_reaction_removed';
  static const chatTypingStarted = 'chat_typing_started';
  static const chatTypingStopped = 'chat_typing_stopped';
  static const chatUnarchived = 'chat_unarchived';
  static const chatUserBlocked = 'chat_user_blocked';
  static const checkoutStarted = 'checkout_started';
  static const checkoutStepCompleted = 'checkout_step_completed';
  static const couponApplied = 'coupon_applied';
  static const couponRemoved = 'coupon_removed';
  static const emailVerified = 'email_verified';
  static const errorOccurred = 'error_occurred';
  static const exportCompleted = 'export_completed';
  static const exportStarted = 'export_started';
  static const featureUsed = 'feature_used';
  static const feedbackSubmitted = 'feedback_submitted';
  static const fileDownloaded = 'file_downloaded';
  static const fileUploaded = 'file_uploaded';
  static const filterApplied = 'filter_applied';
  static const formStart = 'form_start';
  static const formSubmit = 'form_submit';
  static const helpArticleViewed = 'help_article_viewed';
  static const integrationConnected = 'integration_connected';
  static const integrationDisconnected = 'integration_disconnected';
  static const inviteAccepted = 'invite_accepted';
  static const inviteSent = 'invite_sent';
  static const invoiceFailed = 'invoice_failed';
  static const invoicePaid = 'invoice_paid';
  static const mfaDisabled = 'mfa_disabled';
  static const mfaEnabled = 'mfa_enabled';
  static const notificationClicked = 'notification_clicked';
  static const notificationDismissed = 'notification_dismissed';
  static const notificationReceived = 'notification_received';
  static const npsSubmitted = 'nps_submitted';
  static const orderRefunded = 'order_refunded';
  static const passwordResetCompleted = 'password_reset_completed';
  static const passwordResetRequested = 'password_reset_requested';
  static const paymentFailed = 'payment_failed';
  static const paymentMethodAdded = 'payment_method_added';
  static const paymentMethodRemoved = 'payment_method_removed';
  static const paymentSucceeded = 'payment_succeeded';
  static const productListViewed = 'product_list_viewed';
  static const productViewed = 'product_viewed';
  static const purchase = 'purchase';
  static const recommendationClicked = 'recommendation_clicked';
  static const recommendationViewed = 'recommendation_viewed';
  static const refundFailed = 'refund_failed';
  static const removeFromCart = 'remove_from_cart';
  static const screenView = 'screen_view';
  static const scroll = 'scroll';
  static const search = 'search';
  static const searchResultClicked = 'search_result_clicked';
  static const share = 'share';
  static const signin = 'signin';
  static const signout = 'signout';
  static const signup = 'signup';
  static const sortChanged = 'sort_changed';
  static const subscriptionCanceled = 'subscription_canceled';
  static const subscriptionChanged = 'subscription_changed';
  static const subscriptionPaused = 'subscription_paused';
  static const subscriptionRenewed = 'subscription_renewed';
  static const subscriptionResumed = 'subscription_resumed';
  static const subscriptionStarted = 'subscription_started';
  static const subscriptionTrialWillEnd = 'subscription_trial_will_end';
  static const supportChatStarted = 'support_chat_started';
  static const supportTicketCreated = 'support_ticket_created';
  static const supportTicketResolved = 'support_ticket_resolved';
  static const surveyCompleted = 'survey_completed';
  static const surveyStarted = 'survey_started';
  static const trialConverted = 'trial_converted';
  static const trialStarted = 'trial_started';
  static const videoCompleted = 'video_completed';
  static const videoPause = 'video_pause';
  static const videoPlay = 'video_play';
  static const videoSeeked = 'video_seeked';
  static const videoStarted = 'video_started';
  static const wishlistAdded = 'wishlist_added';
  static const wishlistRemoved = 'wishlist_removed';
  static const workspaceCreated = 'workspace_created';
  static const workspaceDeleted = 'workspace_deleted';
  static const workspaceJoined = 'workspace_joined';
  static const workspaceRoleChanged = 'workspace_role_changed';
  static const workspaceSettingsUpdated = 'workspace_settings_updated';

  /// The full set of well-known event kind strings, in the
  /// same order as the per-event constants.
  static const all = <String>[
    addToCart,
    apiKeyCreated,
    apiKeyRevoked,
    appBackgrounded,
    appClose,
    appCrashed,
    appForegrounded,
    appInstall,
    appOpen,
    appUpdate,
    audioCompleted,
    audioPause,
    audioPlay,
    audioSeeked,
    audioStarted,
    cartViewed,
    chatArchived,
    chatAttachmentDownloaded,
    chatAttachmentUploaded,
    chatCallJoined,
    chatCallLeft,
    chatCallRecordingStarted,
    chatCallScreenShared,
    chatCallStarted,
    chatCreated,
    chatDeleted,
    chatJoined,
    chatLeft,
    chatMemberAdded,
    chatMemberMuted,
    chatMemberRemoved,
    chatMemberRoleChanged,
    chatMessageDeleted,
    chatMessageEdited,
    chatMessageFailed,
    chatMessagePinned,
    chatMessageRead,
    chatMessageReceived,
    chatMessageSent,
    chatMessageUnpinned,
    chatReactionAdded,
    chatReactionRemoved,
    chatTypingStarted,
    chatTypingStopped,
    chatUnarchived,
    chatUserBlocked,
    checkoutStarted,
    checkoutStepCompleted,
    couponApplied,
    couponRemoved,
    emailVerified,
    errorOccurred,
    exportCompleted,
    exportStarted,
    featureUsed,
    feedbackSubmitted,
    fileDownloaded,
    fileUploaded,
    filterApplied,
    formStart,
    formSubmit,
    helpArticleViewed,
    integrationConnected,
    integrationDisconnected,
    inviteAccepted,
    inviteSent,
    invoiceFailed,
    invoicePaid,
    mfaDisabled,
    mfaEnabled,
    notificationClicked,
    notificationDismissed,
    notificationReceived,
    npsSubmitted,
    orderRefunded,
    passwordResetCompleted,
    passwordResetRequested,
    paymentFailed,
    paymentMethodAdded,
    paymentMethodRemoved,
    paymentSucceeded,
    productListViewed,
    productViewed,
    purchase,
    recommendationClicked,
    recommendationViewed,
    refundFailed,
    removeFromCart,
    screenView,
    scroll,
    search,
    searchResultClicked,
    share,
    signin,
    signout,
    signup,
    sortChanged,
    subscriptionCanceled,
    subscriptionChanged,
    subscriptionPaused,
    subscriptionRenewed,
    subscriptionResumed,
    subscriptionStarted,
    subscriptionTrialWillEnd,
    supportChatStarted,
    supportTicketCreated,
    supportTicketResolved,
    surveyCompleted,
    surveyStarted,
    trialConverted,
    trialStarted,
    videoCompleted,
    videoPause,
    videoPlay,
    videoSeeked,
    videoStarted,
    wishlistAdded,
    wishlistRemoved,
    workspaceCreated,
    workspaceDeleted,
    workspaceJoined,
    workspaceRoleChanged,
    workspaceSettingsUpdated,
  ];

  /// Returns true when [kind] is a well-known event kind that has a typed
  /// `Pug.track.<event>(...)` method and a `wellKnownEventSchemas` entry.
  static bool isWellKnown(String kind) =>
      wellKnownEventSchemas.containsKey(kind);
}

/// Convenience alias for a free-form property map. Provided so caller
/// code can spell properties consistently as `PugProperties`.
typedef PugProperties = Map<String, Object?>;
